name: hexhunt
description: A comprehensive security scanning tool.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  pdf: ^3.10.7
  file_selector: ^1.0.0
  window_manager: ^0.3.5
  bitsdojo_window: ^0.1.5
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  system_tray: ^2.0.3
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  uuid: ^3.0.7
  flutter_launcher_icons: ^0.14.3
  win32: ^5.0.0
  ffi: ^2.1.0
  path: ^1.8.3
  platform: ^3.1.0
  process: ^4.2.4
  collection: ^1.18.0
  typed_data: ^1.3.2
  http_parser: ^4.0.2
  socket_io_client: ^2.0.3+1
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  x509: ^0.2.0
  network_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "windows/runner/resources/app_icon.ico"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  linux:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 
